---
RecipeFormatVersion: "2020-01-25"
ComponentName: "aws-greengrass-component-sdk.samples.config"
ComponentVersion: "1.0.0"
ComponentType: "aws.greengrass.generic"
ComponentDescription:
  Example component using aws-greengrass-component-sdk to read/write component
  config
ComponentPublisher: AWS
ComponentConfiguration:
  DefaultConfiguration:
    test_str: "hi"
    sample_map:
      key1: "value1"
      key2_map:
        subkey1: "subvalue1"
        subkey2: "subvalue2"
      key3: 10
Manifests:
  - Platform:
      os: linux
      runtime: "*"
    Lifecycle:
      run:
        Script: "{artifacts:path}/sample_config"
    Artifacts:
      - URI: s3://EXAMPLE_BUCKET/sample_config
        Permission:
          Read: "OWNER"
          Execute: "OWNER"
